In [1]:
import pandas as pd
import sklearn 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
bp=pd.read_csv(r"F:\r studio\python\Patient_with_abnormal_bloodpressure.csv")
bp.head()

Patient_Number  Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
0               1                           1                11.28   
1               2                           0                 9.75   
2               3                           1                10.79   
3               4                           0                11.00   
4               5                           1                14.17   

   Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
0                          0.90   34   23    1        1.0        0   
1                          0.23   54   33    1        NaN        0   
2                          0.91   70   49    0        NaN        0   
3                          0.43   71   50    0        NaN        0   
4                          0.83   52   19    0        NaN        0   

   Physical_activity  salt_content_in_the_diet  alcohol_consumption_per_day  \
0              45961                     48071                          NaN   
1              26106                     25333                        205.0   
2               9995                     29465                         67.0   
3              10635                      7439                        242.0   
4              15619                     49644                        397.0   

   Level_of_Stress  Chronic_kidney_disease  Adrenal_and_thyroid_disorders  
0                2                       1                              1  
1                3                       0                              0  
2                2                       1                              0  
3                1                       1                              0  
4                2                       0                              0

In [3]:
bp=bp.drop(['Patient_Number'],axis=1)

In [4]:
bp.head()

Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
0                           1                11.28   
1                           0                 9.75   
2                           1                10.79   
3                           0                11.00   
4                           1                14.17   

   Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
0                          0.90   34   23    1        1.0        0   
1                          0.23   54   33    1        NaN        0   
2                          0.91   70   49    0        NaN        0   
3                          0.43   71   50    0        NaN        0   
4                          0.83   52   19    0        NaN        0   

   Physical_activity  salt_content_in_the_diet  alcohol_consumption_per_day  \
0              45961                     48071                          NaN   
1              26106                     25333                        205.0   
2               9995                     29465                         67.0   
3              10635                      7439                        242.0   
4              15619                     49644                        397.0   

   Level_of_Stress  Chronic_kidney_disease  Adrenal_and_thyroid_disorders  
0                2                       1                              1  
1                3                       0                              0  
2                2                       1                              0  
3                1                       1                              0  
4                2                       0                              0

In [5]:
bp.isnull().sum()

Blood_Pressure_Abnormality          0
Level_of_Hemoglobin                 0
Genetic_Pedigree_Coefficient       92
Age                                 0
BMI                                 0
Sex                                 0
Pregnancy                        1558
Smoking                             0
Physical_activity                   0
salt_content_in_the_diet            0
alcohol_consumption_per_day       242
Level_of_Stress                     0
Chronic_kidney_disease              0
Adrenal_and_thyroid_disorders       0
dtype: int64

In [6]:
bp.Genetic_Pedigree_Coefficient.value_counts()

0.86    32
0.13    30
0.63    28
0.56    27
0.17    27
0.99    26
0.46    25
0.06    25
0.95    25
0.25    25
0.61    24
0.80    24
0.39    24
0.02    24
0.69    23
0.04    23
0.41    23
0.12    23
0.72    23
0.01    23
0.71    22
0.76    22
0.45    22
0.55    22
0.52    22
0.44    21
0.08    21
0.79    21
0.09    21
0.75    21
        ..
0.85    17
0.38    17
0.73    16
0.36    16
0.84    16
0.29    16
0.74    16
0.40    16
0.22    16
0.96    15
0.50    15
0.60    15
0.48    15
0.77    15
0.28    15
0.05    15
0.23    15
0.89    14
0.27    14
0.93    13
0.67    13
0.88    13
0.53    12
0.81    12
0.91    11
0.78    11
0.07    11
0.16    10
0.65     9
0.15     9
Name: Genetic_Pedigree_Coefficient, Length: 101, dtype: int64

In [7]:
bp.Genetic_Pedigree_Coefficient=bp.Genetic_Pedigree_Coefficient.fillna(0)

In [8]:
bp.Pregnancy=bp.Pregnancy.fillna(0)

In [9]:
bp.alcohol_consumption_per_day=bp.alcohol_consumption_per_day.fillna(0)

In [10]:
bp.isnull().sum()

Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [11]:
bp_x=bp.iloc[:,1:]
bp_y=bp.iloc[:,0]

In [12]:
bp_x_train,bp_x_test,bp_y_train,bp_y_test=train_test_split(bp_x,bp_y,test_size=.2)

In [13]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(bp_x_train,bp_y_train)

LogisticRegression()

In [14]:
pred_value=logmodel.predict(bp_x_test)
pred_value

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,

In [15]:
tab1=confusion_matrix(pred_value,bp_y_test)
tab1

array([[103,  69],
       [119, 109]], dtype=int64)

In [16]:
acc1=tab1.diagonal().sum()* 100 / tab1.sum()
acc1

53.0

In [17]:
#DT

In [18]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(bp_x_train,bp_y_train)

DecisionTreeClassifier()

In [19]:
pred_dt=dtree.predict(bp_x_test)
pred_dt

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,

In [20]:
tab2=confusion_matrix(pred_dt,bp_y_test)
tab2

array([[180,  33],
       [ 42, 145]], dtype=int64)

In [21]:
acc2=tab2.diagonal().sum()  *100/tab2.sum()
acc2

81.25

In [22]:
#RF

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(bp_x_train,bp_y_train)

RandomForestClassifier()

In [24]:
pred_rf=rf.predict(bp_x_test)
pred_rf

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,

In [25]:
tab3=confusion_matrix(pred_rf,bp_y_test)
tab3

array([[187,  19],
       [ 35, 159]], dtype=int64)

In [26]:
acc3=tab3.diagonal().sum()  *100/tab3.sum()
acc3

86.5

In [27]:
#SVM

In [28]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(bp_x_train,bp_y_train)

SVC()

In [29]:
pred_svm=svm.predict(bp_x_test)
pred_svm

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,

In [30]:
tab4=confusion_matrix(pred_svm,bp_y_test)
tab4

array([[151, 113],
       [ 71,  65]], dtype=int64)

In [31]:
acc4=tab4.diagonal().sum()  *100/tab4.sum()
acc4

54.0

In [32]:
#ada boost

In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
abc=AdaBoostClassifier(  DecisionTreeClassifier(),n_estimators=15)

In [34]:
abc.fit(bp_x_train,bp_y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=15)

In [35]:
pred_abc=abc.predict(bp_x_test)
pred_abc

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,

In [36]:
tab6=confusion_matrix(pred_abc,bp_y_test)
tab6

array([[181,  34],
       [ 41, 144]], dtype=int64)

In [37]:
acc6=tab6.diagonal().sum()* 100 / tab6.sum()
acc6

81.25

In [38]:
bp_x=bp.iloc[:,1:]
bp_y=bp.iloc[:,0]

In [39]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.tree import DecisionTreeClassifier

In [40]:
test=SelectKBest(score_func=chi2,k='all')
fited=test.fit(bp_x,bp_y)
import numpy as np
print(fited.scores_)

[1.58819593e+01 1.20782029e-02 5.52731166e+01 1.48496735e+01
 3.03838729e+00 4.61940224e-01 1.47217234e-01 2.23949405e+04
 3.26548851e+03 1.48725160e+02 5.83590863e-02 1.82360083e+02
 1.12974982e+02]


In [41]:
feature_importances=pd.DataFrame({'Features':list(bp_x.columns),'Importance':list(fited.scores_)})
feature_importances

Features    Importance
0             Level_of_Hemoglobin     15.881959
1    Genetic_Pedigree_Coefficient      0.012078
2                             Age     55.273117
3                             BMI     14.849674
4                             Sex      3.038387
5                       Pregnancy      0.461940
6                         Smoking      0.147217
7               Physical_activity  22394.940484
8        salt_content_in_the_diet   3265.488508
9     alcohol_consumption_per_day    148.725160
10                Level_of_Stress      0.058359
11         Chronic_kidney_disease    182.360083
12  Adrenal_and_thyroid_disorders    112.974982

In [42]:
bp=bp.drop(['Chronic_kidney_disease','Adrenal_and_thyroid_disorders','Pregnancy','Genetic_Pedigree_Coefficient'],axis=1)

In [43]:
bp_x_train,bp_x_test,bp_y_train,bp_y_test=train_test_split(bp_x,bp_y,test_size=.2)

In [44]:
logmodel.fit(bp_x_train,bp_y_train)

C:\Users\HP SMART\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [45]:
pred_log=logmodel.predict(bp_x_test)
tab7=confusion_matrix(pred_log,bp_y_test)
acc7=tab7.diagonal().sum()* 100 / tab7.sum()
acc7

51.5

In [46]:
dtree.fit(bp_x_train,bp_y_train)
pred_dt2=dtree.predict(bp_x_test)
tab8=confusion_matrix(pred_dt2,bp_y_test)
acc8=tab8.diagonal().sum()* 100 / tab8.sum()
acc8

82.5

In [47]:
rf.fit(bp_x_train,bp_y_train)
pred_rf2=rf.predict(bp_x_test)
tab9=confusion_matrix(pred_rf2,bp_y_test)
acc9=tab9.diagonal().sum()* 100 / tab9.sum()
acc9

88.25

In [48]:
svm.fit(bp_x_train,bp_y_train)
pred_svm2=svm.predict(bp_x_test)
tab10=confusion_matrix(pred_svm2,bp_y_test)
acc10=tab10.diagonal().sum()* 100 / tab10.sum()
acc10

49.0

In [49]:
abc.fit(bp_x_train,bp_y_train)
pred_abc2=abc.predict(bp_x_test)
tab11=confusion_matrix(pred_abc2,bp_y_test)
acc11=tab11.diagonal().sum()* 100 / tab11.sum()
acc11

81.5

In [50]:
accuracy=pd.DataFrame({'model':('logistic','decision_tree','random_forest','svm','adaboost'),'before':(acc1,acc2,acc3,acc4,acc6),'after':(acc7,acc8,acc9,acc10,acc11)})
accuracy

after  before          model
0  51.50   53.00       logistic
1  82.50   81.25  decision_tree
2  88.25   86.50  random_forest
3  49.00   54.00            svm
4  81.50   81.25       adaboost

In [53]:
from sklearn.model_selection import cross_val_score

In [54]:
scores_logmodel=cross_val_score(logmodel,bp_x,bp_y,cv=7,scoring='accuracy')
scores_logmodel

C:\Users\HP SMART\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\HP SMART\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logist

array([0.53496503, 0.53846154, 0.50699301, 0.57342657, 0.72027972,
       0.56491228, 0.56491228])

In [55]:
scores_logmodel.mean()

0.5719929193613404

In [56]:
scores_dt=cross_val_score(dtree,bp_x,bp_y,cv=7,scoring='accuracy')
scores_dt
scores_dt.mean()

0.8365020943968313

In [57]:
scores_rf=cross_val_score(rf,bp_x,bp_y,cv=7,scoring='accuracy')
scores_rf
scores_rf.mean()

0.8729919203603416